name: CloneGithubReleases.
on:
  # kick off the job on demand
  workflow_dispatch:
  # and run on a schedule every 12 hours
  schedule:
    - cron: "* */24 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: andrewthetechie/gha-clone-releases@v1.9.0
        with:
          token: ${{ secrets.GAZEPANNINGACCESS }}
          src_repo: https://github.com/rubyleehs/Gaze-Panning.git
